export enum Roles {
  ADMIN = 'ADMIN',
  PSICOLOGO = 'PSICOLOGO',
  PSIQUIATRA = 'PSIQUIATRA',
  SECRETARIO = 'SECRETARIO',
  USER = 'USER',
}

export enum EstadoCita {
  PENDIENTE = 'PENDIENTE',
  CONFIRMADA = 'CONFIRMADA',
  CANCELADA = 'CANCELADA',
  COMPLETADA = 'COMPLETADA',
  NO_ASISTIO = 'NO_ASISTIO',
}

export enum EstadoFactura {
  BORRADOR = 'BORRADOR',
  EMITIDA = 'EMITIDA',
  PAGADA = 'PAGADA',
  ANULADA = 'ANULADA',
}